### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data_capture'

### ISSUE THREAD

**Issue by Coffeeye** [jayatsandia/svp_1547.1#37]
![image](https://user-images.githubusercontent.com/83951742/164713190-c65d0595-3bfd-4472-b863-94f0b49417fe.png)

**Comment by jayatsandia** [comment]
You will need to configure a data acquisition system in the Test or Suite in order to run this script.

**Comment by Coffeeye** [comment]
![image](https://user-images.githubusercontent.com/83951742/165028905-428f1b9d-bc4b-4642-8211-8be4e2296f07.png)

How about script them selfs? Are they need to be set-up somehow as well?
